using System.Collections.Generic;
using EasySave.WPF.Enumerations;

namespace EasySave.WPF.Config
{
    public static class ResourceSettings
    {
        private static readonly Dictionary<string, string> _fr = new Dictionary<string, string>
        {
            { "JobName", "Nom du travail" },
            { "TabHome", "Accueil" },
            { "TabSettings", "Configuration" },
            { "TitleSettings", "Paramètres Généraux" },
            { "State", "État" },
            { "SourcePath", "Dossier Source" },
            { "TargetPath", "Dossier Cible" },
            { "Type", "Type" },
            { "Encrypt", "Encrypt" },
            { "Create", "Créer" },
            { "Modify", "Modifier" },
            { "Update", "Mettre à jour" },
            { "Delete", "Supprimer" },
            { "Execute", "Exécuter" },
            { "StatusReady", "Prêt." },
            { "LogFormat", "Format des Logs :" },
            { "LangInterface", "Langue de l'interface :" },
            { "EncryptExtensions", "Extensions à encrypter :" },
            { "EncryptAll", "Encrypter tous les fichiers" },
            { "AddExtension", "Ajouter" },
            { "BlockedProcesses", "Processus Métiers :" },
            { "AddProcess", "Ajouter Processus" },
            { "General", "Général" },
            { "Encryption", "Chiffrement" },
            { "LogFormatDesc", "Format des fichiers de log" },
            { "LangInterfaceDesc", "Langue de l'application" },
            { "EncryptAllDesc", "Chiffrer tous les fichiers" },
            { "BlockedProcessesDesc", "La sauvegarde se mettra en pause si ces processus sont détectés" },
            { "Success", "Succès" },
            { "Error", "Erreur" },
            { "EmptyFields", "Champs vides !" },
            { "JobCreated", "créé." },
            { "ConfirmDeleteSingle", "Êtes-vous sûr de vouloir supprimer le travail '{0}' ?" },
            { "ConfirmDeleteMultiple", "Êtes-vous sûr de vouloir supprimer les {0} travaux sélectionnés ?" },
            { "JobDeleted", "Travail supprimé." },
            { "ExecutingJobs", "Exécution de {0} travaux..." },
            { "JobFinished", "terminé !" },
            { "Status", "Statut :" },
            { "LogServerIP", "IP du serveur de Logs :" },
            { "LogServerIPDesc", "Adresse IP pour les logs distants" },
            { "ProcessBlockedMessage", "Le processus '{0}' est en cours d'exécution et doit être fermé pour continuer la sauvegarde." },
            { "Directories", "Répertoires" },
            { "Progress", "Progression" },
            { "SelectedJobs", "Travaux sélectionnés :" },
            { "Transfer", "Transfert" },
            { "Throughput", "Débit" },
            { "JobsPaused", "Travaux en pause." },
            { "JobsResumed", "Travaux repris." },
            { "JobsStopped", "Travaux arrêtés." },
            { "Full", "Complète" },
            { "Differential", "Différentielle" },
            { "PriorityExtensions", "Extensions prioritaires" },
            { "PriorityExtensionsDesc", "Ces fichiers seront copiés en premier (ex: .txt, .pdf)" },
            { "ConsoleMenuTitle", "EASYSAVE V3.0 - MODE CONSOLE" },
            { "ConsoleMenuShow", "1. Afficher les travaux" },
            { "ConsoleMenuExec", "2. Exécuter un travail" },
            { "ConsoleMenuCreate", "3. Créer un travail" },
            { "ConsoleMenuSet", "4. Paramètres" },
            { "ConsoleMenuQuit", "5. Quitter" },
            { "ConsoleChoice", "Votre choix : " },
            { "ConsoleCreateTitle", "CRÉATION D'UN TRAVAIL" },
            { "ConsoleAddName", "Nom du travail : " },
            { "ConsoleAddSource", "Chemin source (ex: C:\\Dossier) : " },
            { "ConsoleAddTarget", "Chemin cible (ex: D:\\Backup) : " },
            { "ConsoleAddType", "Type (0 = Complet, 1 = Différentiel) : " },
            { "ConsoleJobListTitle", "--- Liste des travaux ---" },
            { "ConsoleNoJobs", "Aucun travail configuré." },
            { "ConsolePressEnter", "\nAppuyez sur Entrée pour revenir..." },
            { "ConsoleEnterJobNumber", "Entrez le numéro du travail à exécuter (ou laissez vide pour annuler) : " },
            { "ConsoleLaunchingJob", "\nLancement de '{0}'..." },
            { "ConsoleJobFinished", "\nTravail terminé ! Appuyez sur Entrée..." },
            { "ConsoleSettingsTitle", "PARAMÈTRES" },
            { "ConsoleSettingsLang", "1. Langue : " },
            { "ConsoleSettingsLogFormat", "2. Format des Logs : " },
            { "ConsoleSettingsIP", "3. IP du Serveur Logs : " },
            { "ConsoleSettingsEncryptAll", "4. Chiffrer TOUT : " },
            { "ConsoleSettingsBack", "5. Retour au menu principal" },
            { "ConsoleSettingsModify", "Que voulez-vous modifier ? : " },
            { "ConsoleSettingsChooseLang", "Choisissez la langue (0 pour Anglais, 1 pour Français) : " },
            { "ConsoleSettingsLangChanged", "Langue modifiée !" },
            { "ConsoleSettingsChooseFormat", "Format (json, xml, network, json+network, xml+network) : " },
            { "ConsoleSettingsFormatChanged", "Format modifié !" },
            { "ConsoleSettingsChooseIP", "Nouvelle IP du serveur de logs : " },
            { "ConsoleSettingsIPChanged", "IP modifiée !" },
            { "ConsoleSettingsEncryptToggled", "Paramètre de chiffrement inversé !" },
            { "ConsoleSettingsContinue", "Appuyez sur Entrée pour continuer..." },
            { "RestartWarning", "Le changement de langue nécessitera un redémarrage pour être complet." }
        };

        private static readonly Dictionary<string, string> _en = new Dictionary<string, string>
        {
            { "JobName", "Job Name" },
            { "TabHome", "Home" },
            { "TabSettings", "Settings" },
            { "TitleSettings", "General Settings" },
            { "State", "State" },
            { "SourcePath", "Source Folder" },
            { "TargetPath", "Target Folder" },
            { "Type", "Type" },
            { "Encrypt", "Encrypt" },
            { "Create", "Create" },
            { "Modify", "Modify" },
            { "Update", "Update" },
            { "Delete", "Delete" },
            { "Execute", "Execute" },
            { "StatusReady", "Ready." },
            { "LogFormat", "Log Format :" },
            { "LangInterface", "Interface Language :" },
            { "EncryptExtensions", "Extensions to encrypt :" },
            { "EncryptAll", "Encrypt all files" },
            { "AddExtension", "Add" },
            { "BlockedProcesses", "Business Processes :" },
            { "AddProcess", "Add Process" },
            { "General", "General" },
            { "Encryption", "Encryption" },
            { "LogFormatDesc", "Format of log files" },
            { "LangInterfaceDesc", "Application language" },
            { "EncryptAllDesc", "Encrypt all files" },
            { "BlockedProcessesDesc", "The backup will pause if these processes are detected" },
            { "Success", "Success" },
            { "Error", "Error" },
            { "EmptyFields", "Empty fields !" },
            { "JobCreated", "created." },
            { "ConfirmDeleteSingle", "Are you sure you want to delete the job '{0}'?" },
            { "ConfirmDeleteMultiple", "Are you sure you want to delete the {0} selected jobs?" },
            { "JobDeleted", "Job deleted." },
            { "ExecutingJobs", "Executing {0} jobs..." },
            { "JobFinished", "finished !" },
            { "Status", "Status :" },
            { "LogServerIP", "Log Server IP :" },
            { "LogServerIPDesc", "IP address for remote logs" },
            { "ProcessBlockedMessage", "The process '{0}' is running and must be closed to continue the backup." },
            { "Directories", "Directories" },
            { "Progress", "Progress" },
            { "SelectedJobs", "Selected Jobs:" },
            { "Transfer", "Transfer" },
            { "Throughput", "Throughput" },
            { "JobsPaused", "Jobs paused." },
            { "JobsResumed", "Jobs resumed." },
            { "JobsStopped", "Jobs stopped." },
            { "Full", "Full" },
            { "Differential", "Differential" },
            { "PriorityExtensions", "Priority Extensions" },
            { "PriorityExtensionsDesc", "These files will be copied first (e.g., .txt, .pdf)" },
            { "ConsoleMenuTitle", "EASYSAVE V3.0 - CONSOLE MODE" },
            { "ConsoleMenuShow", "1. Show backup jobs" },
            { "ConsoleMenuExec", "2. Execute a job" },
            { "ConsoleMenuCreate", "3. Create a job" },
            { "ConsoleMenuSet", "4. Settings" },
            { "ConsoleMenuQuit", "5. Quit" },
            { "ConsoleChoice", "Your choice: " },
            { "ConsoleCreateTitle", "CREATING A JOB" },
            { "ConsoleAddName", "Job name: " },
            { "ConsoleAddSource", "Source path (e.g., C:\\Folder): " },
            { "ConsoleAddTarget", "Target path (e.g., D:\\Backup): " },
            { "ConsoleAddType", "Type (0 = Full, 1 = Differential): " },
            { "ConsoleJobListTitle", "--- Backup Jobs List ---" },
            { "ConsoleNoJobs", "No jobs configured." },
            { "ConsolePressEnter", "\nPress Enter to return..." },
            { "ConsoleEnterJobNumber", "Enter the job number to execute (or leave blank to cancel): " },
            { "ConsoleLaunchingJob", "\nLaunching '{0}'..." },
            { "ConsoleJobFinished", "\nJob finished! Press Enter..." },
            { "ConsoleSettingsTitle", "SETTINGS" },
            { "ConsoleSettingsLang", "1. Language: " },
            { "ConsoleSettingsLogFormat", "2. Log Format: " },
            { "ConsoleSettingsIP", "3. Log Server IP: " },
            { "ConsoleSettingsEncryptAll", "4. Encrypt ALL: " },
            { "ConsoleSettingsBack", "5. Back to main menu" },
            { "ConsoleSettingsModify", "What do you want to modify?: " },
            { "ConsoleSettingsChooseLang", "Choose language (0 for English, 1 for French): " },
            { "ConsoleSettingsLangChanged", "Language modified!" },
            { "ConsoleSettingsChooseFormat", "Format (json, xml, network, json+network, xml+network): " },
            { "ConsoleSettingsFormatChanged", "Format modified!" },
            { "ConsoleSettingsChooseIP", "New Log Server IP: " },
            { "ConsoleSettingsIPChanged", "IP modified!" },
            { "ConsoleSettingsEncryptToggled", "Encryption setting toggled!" },
            { "ConsoleSettingsContinue", "Press Enter to continue..." },
            { "RestartWarning", "Language change requires a restart to be fully applied." }
        };

        public static string GetString(string key)
        {
            var currentLang = AppSettings.Instance.Language;

            var dict = currentLang == Language.Francais ? _fr : _en;

            return dict.ContainsKey(key) ? dict[key] : $"[{key}]";
        }
    }
}